#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# For auto updating
DISABLE_UPDATE_PROMPT=true

# For z
. `brew --prefix`/etc/profile.d/z.sh

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH=/usr/local/git/bin:/usr/local/bin:$PATH
export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH

# bower
alias bower='noglob bower'
eval $(thefuck --alias)

# aliases
alias c='clear'
alias zen='defaults write com.apple.finder CreateDesktop -bool false && killall Finder'
alias unzen='defaults write com.apple.finder CreateDesktop -bool true && killall Finder'

# added by travis gem
[ -f /Users/samnnodim/.travis/travis.sh ] && source /Users/samnnodim/.travis/travis.sh




